name: Build
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install Dependencies
      run: npm install --no-audit
    - name: License Check
      run: npx license-checker --summary --onlyAllow "Apache-2.0;MIT;BSD-3-Clause;BSD-2-Clause;ISC;CC0-1.0;MPL-2.0;CC-BY-4.0;ODC-By-1.0;WTFPL;CC-BY-3.0;0BSD"
      continue-on-error: true
    - name: Audit Dependencies
      run: npm audit --production
    - name: Build
      run: BUILD_VERSION=$GITHUB_SHA npm run build
    - name: Push Build
      run: ./push_build.sh
